# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traget2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 20, 500, 61))
        self.label.setStyleSheet("font: 75 30pt \"\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 440, 350))
        self.label_2.setStyleSheet("background-color:rgb;\n"
"border-radius: 20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 420, 330))
        self.label_3.setStyleSheet("background-color: rgb(37, 86, 193);\n"
"border-radius: 20px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_show = QtWidgets.QLabel(self.centralwidget)
        self.label_show.setGeometry(QtCore.QRect(50, 170, 400, 310))
        self.label_show.setStyleSheet("background-color:black;\n"
"border-radius: 20px;")
        self.label_show.setText("")
        self.label_show.setObjectName("label_show")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(510, 150, 530, 411))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton_pic = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pic.setGeometry(QtCore.QRect(30, 520, 130, 41))
        self.pushButton_pic.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"font: 12pt \"\";\n"
"border-radius: 8px;")
        self.pushButton_pic.setObjectName("pushButton_pic")
        self.pushButton_camera = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_camera.setGeometry(QtCore.QRect(180, 520, 130, 41))
        self.pushButton_camera.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"font: 12pt \"\";\n"
"border-radius: 8px;")
        self.pushButton_camera.setObjectName("pushButton_camera")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(540, 160, 300, 31))
        self.label_6.setStyleSheet("background-color: transparent;\n"
"font: 18pt \"\";")
        self.label_6.setObjectName("label_6")
        # self.line = QtWidgets.QFrame(self.centralwidget)
        # self.line.setGeometry(QtCore.QRect(530, 200, 350, 1))
        # self.line.setFrameShape(QtWidgets.QFrame.HLine)
        # self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.line.setStyleSheet("border: 1px solid black;")
        # self.line.setObjectName("line")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(540, 220, 85, 31))
        self.label_7.setStyleSheet("background-color: transparent;\n"
"font: 15pt \"\";")
        self.label_7.setObjectName("label_7")
        self.label_type = QtWidgets.QLabel(self.centralwidget)
        self.label_type.setGeometry(QtCore.QRect(630, 220, 80, 31))
        self.label_type.setStyleSheet("background-color: transparent;\n"
"color: rgb(236, 0, 0);\n"
"font: 15pt \"\";")
        self.label_type.setObjectName("label_type")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(710, 220, 110, 31))
        self.label_9.setStyleSheet("background-color: transparent;\n"
"font: 15pt \"\";")
        self.label_9.setObjectName("label_9")
        self.label_pro = QtWidgets.QLabel(self.centralwidget)
        self.label_pro.setGeometry(QtCore.QRect(830, 220, 61, 31))
        self.label_pro.setStyleSheet("background-color: transparent;\n"
"font: 18pt \"\";\n"
"color: rgb(236, 0, 0);")
        self.label_pro.setObjectName("label_pro")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(540, 330, 300, 31))
        self.label_11.setStyleSheet("background-color: transparent;\n"
"font: 18pt \"\";")
        self.label_11.setObjectName("label_11")
        # self.line_2 = QtWidgets.QFrame(self.centralwidget)
        # self.line_2.setGeometry(QtCore.QRect(530, 370, 350, 1))
        # self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        # self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.line_2.setObjectName("line_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 10, 121, 41))
        self.label_12.setStyleSheet("font: 75 18pt \"\";\n"
"color: rgb(0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 60, 61, 51))
        self.label_13.setStyleSheet("font: 75 35pt \"\";\n"
"color: rgb(0, 0, 0);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(820, 100, 300, 31))
        self.label_14.setStyleSheet("background-color: transparent;\n"
"font: 12pt \"\";")
        self.label_14.setObjectName("label_14")
        self.pushButton_video = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_video.setGeometry(QtCore.QRect(340, 520, 131, 41))
        self.pushButton_video.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"font: 12pt \"\";\n"
"border-radius: 8px;")
        self.pushButton_video.setObjectName("pushButton_video")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(540, 270, 71, 31))
        self.label_8.setStyleSheet("background-color: transparent;\n"
"font: 18pt \"\";")
        self.label_8.setObjectName("label_8")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(620, 270, 81, 31))
        self.label_time.setStyleSheet("background-color: transparent;\n"
"color: rgb(236, 0, 0);\n"
"font: 18pt \"\";")
        self.label_time.setObjectName("label_time")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(710, 270, 111, 31))
        self.label_10.setStyleSheet("background-color: transparent;\n"
"font: 18pt \"\";")
        self.label_10.setObjectName("label_10")
        self.label_num = QtWidgets.QLabel(self.centralwidget)
        self.label_num.setGeometry(QtCore.QRect(820, 270, 51, 31))
        self.label_num.setStyleSheet("background-color: transparent;\n"
"color: rgb(236, 0, 0);\n"
"font: 18pt \"\";")
        self.label_num.setObjectName("label_num")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(530, 380, 500, 171))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 1050, 600))
        self.label_15.setStyleSheet("background-color: rgb(224, 243, 250); ")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(530, 190, 500, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(530, 360, 500, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_15.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_show.raise_()
        self.pushButton_pic.raise_()
        self.pushButton_camera.raise_()
        self.label_6.raise_()
        # self.line.raise_()
        self.label_7.raise_()
        self.label_type.raise_()
        self.label_9.raise_()
        self.label_pro.raise_()
        self.label_11.raise_()
        # self.line_2.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.pushButton_video.raise_()
        self.label_8.raise_()
        self.label_time.raise_()
        self.label_10.raise_()
        self.label_num.raise_()
        self.tableWidget.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Waste classification"))
        self.label.setText(_translate("MainWindow", "Waste classification "))
        self.pushButton_pic.setText(_translate("MainWindow", "Select an image"))
        self.pushButton_camera.setText(_translate("MainWindow", "Camera detection"))
        self.label_6.setText(_translate("MainWindow", "Identify the results"))
        self.label_7.setText(_translate("MainWindow", "category："))
        self.label_type.setText(_translate("MainWindow", "1"))
        self.label_9.setText(_translate("MainWindow", "Confidence："))
        self.label_pro.setText(_translate("MainWindow", "100%"))
        self.label_11.setText(_translate("MainWindow", "Results information"))
        self.label_12.setText(_translate("MainWindow", "2024/8"))
        self.label_13.setText(_translate("MainWindow", "20"))
        self.label_14.setText(_translate("MainWindow", "Author：Taojie Chen"))
        self.pushButton_video.setText(_translate("MainWindow", "Select Video"))
        self.label_8.setText(_translate("MainWindow", "Time："))
        self.label_time.setText(_translate("MainWindow", "1s"))
        self.label_10.setText(_translate("MainWindow", "Amount："))
        self.label_num.setText(_translate("MainWindow", "9"))

